sudo: required
services:
  - docker
env:
  - CI_TYPE=TRAVIS
  - CI_TYPE=JENKINS
script:
  - docker build -t johnlinvc/danger-ci .
  - ./gen_env.rb > travis-ci.env
  - cat travis-ci.env
  - docker run --env-file travis-ci.env -v `pwd`:/app johnlinvc/danger-ci
